import turtle
pen = turtle.Turtle()
pen.screen.bgcolor('black')
pen.pensize(5)
pen.pencolor("red")
#pen.speed(10000)
def curve():
    for i in range(200):
        pen.right(1)
        pen.forward(1)
def heart():
    pen.fillcolor('white')
    pen.begin_fill()
    pen.left(140)
    pen.forward(113)
    curve()
    pen.left(120)
    curve()
    pen.forward(112)
    pen.end_fill()
def txt():
    pen.up()
    pen.setpos(-68, 95)
    pen.down()
    pen.color('red')
    pen.write(" Love You", font=("calibric", 22, "italic"))
heart()
txt()
pen.ht()
turtle.done()