import turtle
t=turtle.Turtle()
t.screen.bgcolor('black')
t.pensize(2)
t.color('red')
t.left(90)
t.backward(100)
t.speed(30000)
t.shape('turtle')
def tree(i):
    if i<10:
        return
    else:
        t.forward(i)
        t.color('yellow')
        t.circle(2)
        t.color('red')
        t.left(30)
        tree(3*i/4)
        t.right(60)
        tree(3*i/4)
        t.left(30)
        t.backward(i)
tree(100)
t.pencolor('red')
t.hideturtle()
t.right(90)
t.up()
t.forward(200)
t.write("Hello there!",move="false", align="center", font=("Jokerman", 25, "italic"))
turtle.done()